#!/usr/bin/env bash
# Redirect every pop-os/libcosmic git dependency to the SoryOS fork checkout.
# Expects libcosmic as a sibling of cosmic-epoch:
#   <work-dir>/cosmic-epoch/
#   <work-dir>/libcosmic/
set -euo pipefail

COSMIC_EPOCH_DIR="${1:-}"
LIBCOSMIC_DIR="${2:-}"

if [[ -z "$COSMIC_EPOCH_DIR" || -z "$LIBCOSMIC_DIR" ]]; then
  printf 'usage: %s <cosmic-epoch-dir> <libcosmic-dir>\n' "$0" >&2
  exit 2
fi

COSMIC_EPOCH_DIR="$(cd "$COSMIC_EPOCH_DIR" && pwd)"
LIBCOSMIC_DIR="$(cd "$LIBCOSMIC_DIR" && pwd)"

if [[ ! -f "$LIBCOSMIC_DIR/Cargo.toml" ]]; then
  printf 'libcosmic checkout not found: %s\n' "$LIBCOSMIC_DIR" >&2
  exit 1
fi

mkdir -p "$COSMIC_EPOCH_DIR/.cargo"

# Paths are relative to cosmic-epoch/.cargo/config.toml
cat > "$COSMIC_EPOCH_DIR/.cargo/config.toml" <<'EOF'
# SoryOS: force all COSMIC apps to build against our libcosmic fork (sibling ../libcosmic).
# Generated by sory-os-apt/scripts/install-libcosmic-patch.sh — do not edit by hand.

EOF

patch_block() {
  local url="$1"
  cat >> "$COSMIC_EPOCH_DIR/.cargo/config.toml" <<EOF

[patch."$url"]
libcosmic = { path = "../libcosmic" }
cosmic-config = { path = "../libcosmic/cosmic-config" }
cosmic-theme = { path = "../libcosmic/cosmic-theme" }
iced_futures = { path = "../libcosmic/iced/futures" }
iced_winit = { path = "../libcosmic/iced/winit" }
iced_tiny_skia = { path = "../libcosmic/iced/tiny_skia" }
iced_graphics = { path = "../libcosmic/iced/graphics" }
iced_core = { path = "../libcosmic/iced/core" }
iced_wgpu = { path = "../libcosmic/iced/wgpu" }
iced_renderer = { path = "../libcosmic/iced/renderer" }
EOF
}

for url in \
  "https://github.com/pop-os/libcosmic" \
  "https://github.com/pop-os/libcosmic.git" \
  "https://github.com/pop-os/libcosmic/" \
  "https://github.com/pop-os/libcosmic//"
do
  patch_block "$url"
done

printf 'installed libcosmic cargo patch:\n'
printf '  cosmic-epoch: %s/.cargo/config.toml\n' "$COSMIC_EPOCH_DIR"
printf '  libcosmic:    %s\n' "$LIBCOSMIC_DIR"
